development:
  adapter: postgresql
  encoding: unicode
  database: postgres_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: postgres_test
  pool: 5â€‹
production:
  adapter: postgresql
  encoding: unicode
  database: postgres_production
  pool: 5
